[package]
name = "bgmrank"
version = "0.1.0"
authors = ["Xidorn Quan <quanxunzhen@gmail.com>"]

[dependencies]
getopts = "0.2"
enum-set = "0.0.6"
selectors = "0.12"
string_cache = "0.2"

[dependencies.kuchiki]
version = "0.3"
features = ["hyper"]
