[package]
name = "libbgmrank"
version = "0.0.1"
authors = ["Xidorn Quan <me@upsuper.org>"]

[dependencies]
enum-set = "0.0.6"
selectors = "0.14"
html5ever-atoms = "0.1.2"

[dependencies.kuchiki]
version = "0.4"
features = ["hyper"]
